### PR TITLE
react16 support

### PR DESCRIPTION
**Pull request by pcross616**
major deps upgrades and webpack configuration changes.

### CODE REVIEW

**Comment by pcross616** [comment]
Updated project to support React 16 see issue #40 
Pulled in #44 and #35

**Comment by Raathigesh** [comment]
Hey @pcross616, Thank for doing this. Would you be interested if l I add you as a collaborator on the project?

**Comment by pcross616** [comment]
@Raathigesh sure.

**Comment by Raathigesh** [comment]
Done

**Pull request merged**
