### PR TITLE
Added DashboardWithoutDndContext export that has no react-dnd DragDropContext

### PR DESCRIPTION
**Pull request by khelkun**
Here is the PR related to our previous discussion [#31](https://github.com/Raathigesh/dazzle/issues/31) To be honest I think this is my very first PR on github!

I'm still not very comfortable with ES6/7 modules so please feel free to edit this if it's not right. I've not added a test but I'm not sure it's necessary. However I can confirm _Dashboard_ and _DashboardWithoutDndContext_ components run has expected in my React application.

### CODE REVIEW

**Comment by Raathigesh** [comment]
This is awesome. Thank you! I would put the details that you have added to the readme to a separate file and link it. But, I'll do that when I merge.

I'll merge this during the weekend and push a release. 

Again, thank you for the PR and welcome to open-source. Keep contributing!

**Comment by khelkun** [comment]
@Raathigesh You're welcome. I thank you. If you can release the npm package after the merge that would be great.

**Comment by doppelgunner** [comment]
What happened? no time for merging? When will the merge be? Thanks in advance. Im hoping it will be soon.

**Comment by freenetbrasil** [comment]
Hopes this gets merged soon!

**Comment by khelkun** [comment]
Hello @Raathigesh, would you have some time to merge this PR please?

**Comment by pcross616** [comment]
Looks like it's code coverage issues

**Pull request merged**
